Repository ChilloutCharles/BrainFlowsIntoVRChat, pull requests merged in 2024-06, with the labels that each got.

#30 Fix UnboundLocalError on failed init
  main.py
Labels: bug, quality of life

#29 Self training convenience
  model/intent/README.md
  model/intent/record_eeg.py
  model/intent/train.py
Labels: enhancement, good first issue, quality of life

#31 Self Supervised Model
  .gitignore
  README.md
  logic/ml_action.py
  main.py
  model/intent/README.md
  model/intent/blank.png
  model/intent/edf_parser.py
  model/intent/edf_train.py
  model/intent/fireball.png
  model/intent/model.py
  model/intent/physionet_decoder.keras
  model/intent/physionet_downloader.py
  model/intent/physionet_encoder.keras
  model/intent/pipeline.py
  model/intent/record_eeg.py
  model/intent/train.py
  requirements.txt
Labels: enhancement
